#region Using directives

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

#endregion

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("TradeWright.TabControlExtraDemo")]
[assembly: AssemblyDescription("Displays various tab styles generated by the TabControlExtra component.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Richard L King (TradeWright Software Systems)")]
[assembly: AssemblyProduct("TabControlExtraDemo")]
[assembly: AssemblyCopyright("Copyright © Mark Jackson 2010; Richard L King 2012-2018")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en-GB")]
[assembly: CLSCompliant(true)]

// This sets the default COM visibility of types in the assembly to invisible.
// If you need to expose a type to COM, use [ComVisible(true)] on that type.
[assembly: ComVisible(false)]

// The assembly version has following format :
//
// Major.Minor.Build.Revision
//
// You can specify all the values or you can use the default the Revision and 
// Build Numbers by using the '*' as shown below:
[assembly: AssemblyVersion("2.0.0")]
